### ISSUE TITLE
file-folder demo

### ISSUE THREAD

**Issue by maxwowpow** [winhowes/file-tree#1]
Hello,
if I understand correctly `file-folder` is used to store another `file-folder` like

```
<file-folder name="Folder1">
 <file-folder name="Folder2"></file-folder>
</file-folder>
```

Could you please write a small demo for that, because I couldn't get it working. Iron Page is only for the `file-tree` component

**Comment by winhowes** [comment]
The `file-folder` takes in a data object just like the `file-tree`. The key difference is that the `file-tree` keeps track of which folder is selected. In normal use it probably doesn't make sense to use the `file-folder` element on its own, but passing in the same data object to a `file-folder` element as is passed into the `file-tree` element like in the demo will render the same hierarchy.
